#!/bin/sh
### BEGIN INIT INFO
# Provides:          umrc
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     4 5
# Default-Stop:      0 1 6
# Description:       IRC bot to control a mastodon account
### END INIT INFO

if test -f /etc/default/umrc; then
  . /etc/default/umrc
else
  "Missing /etc/default/umrc"
  exit
fi

PIDFILE=/var/run/umrc.pid

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT \"$CONFIG\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(head -1 "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(head -1 "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
